# Generated by Django 4.2.30 on 2026-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("sales", "Sales"), ("purchase", "Purchase")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("party_name", models.CharField(max_length=200)),
                ("invoice_date", models.DateField()),
                ("currency", models.CharField(default="SAR", max_length=10)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=15, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-invoice_date", "-id"],
            },
        ),
    ]
