# Generated by Django 4.2.30 on 2026-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="zatca_category",
            field=models.CharField(blank=True, default="S", max_length=1),
        ),
    ]
