# Generated by Django 4.2.30 on 2026-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0002_invoice_zatca_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
