# Generated by Django 4.2.30 on 2026-07-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_tenant"),
        ("invoicing", "0004_invoice_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Which company this invoice belongs to. Nullable for backward compatibility with rows created before this field existed; post_to_ledger() falls back to the oldest company if unset.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="core.companyprofile",
            ),
        ),
    ]
