# Generated by Django 4.2.30 on 2026-07-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("core", "0004_user_tenant"),
        ("invoicing", "0005_invoice_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_number", models.CharField(max_length=50, unique=True)),
                ("credit_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("posted", "Posted")],
                        db_index=True,
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes",
                        to="core.companyprofile",
                    ),
                ),
                (
                    "original_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "credit_notes",
                "ordering": ["-credit_date", "-id"],
            },
        ),
    ]
