# Generated by Django 4.2.30 on 2026-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0007_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="Rate to base currency at invoice date",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="Rate to base currency at payment date",
                max_digits=14,
            ),
        ),
    ]
