# Generated by Django 4.2.30 on 2026-07-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0003_project_actual_end_date_project_actual_start_date_and_more'),
        ('core', '0004_user_tenant'),
        ('selling', '0001_initial'),
        ('accounts', '0004_accountingperiod'),
        ('buying', '0003_purchaseorder_billed_amount_and_more'),
        ('inventory', '0001_initial'),
        ('invoicing', '0008_invoice_exchange_rate_payment_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='against_purchase_order',
            field=models.ForeignKey(blank=True, help_text='Purchase Order this invoice was generated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='buying.purchaseorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='against_sales_order',
            field=models.ForeignKey(blank=True, help_text='Sales Order this invoice was generated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='selling.salesorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text="Cost center this invoice's revenue/expense is attributed to.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='accounts.costcenter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Document-level discount, subtracted from subtotal before arriving at total. Mirrors SalesOrder.discount / PurchaseOrder.discount so an order converts to an invoice without silently dropping the discount the customer was quoted.', max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this invoice bills against, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pmo.project'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=15, max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoicing.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.item')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.warehouse')),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['id'],
            },
        ),
    ]
