# Generated by Django 4.2.30 on 2026-07-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('invoicing', '0009_invoice_against_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="BRN-CTRL-004: which branch this invoice's revenue/expense belongs to. Invoices carried no branch at all, so nothing a branch earned could be attributed back to it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.branch'),
        ),
    ]
