# Generated by Django 4.2 on 2026-07-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('useful_life_years', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disposed', 'Disposed'), ('Sold', 'Sold')], default='Active', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.company')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory')),
            ],
        ),
    ]
