# Generated by Django 4.2.30 on 2026-07-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("name_ar", models.CharField(blank=True, max_length=80)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("is_base", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rate_to_base",
                    models.DecimalField(decimal_places=6, default=1, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "currencies",
                "ordering": ["-is_base", "code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_to_base", models.DecimalField(decimal_places=6, max_digits=14)),
                ("date", models.DateField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "db_table": "exchange_rates",
                "ordering": ["-date"],
            },
        ),
    ]
