# Generated by Django 4.2.30 on 2026-07-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_binlocation_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='bin_location',
            field=models.ForeignKey(blank=True, help_text='WHS-CTRL-001: required once the warehouse has bins defined.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='core.binlocation'),
        ),
    ]
