# Generated by Django 4.2.30 on 2026-07-18 09:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockentry_bin_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text="Always positive. Direction comes from entry_type (Receipt adds, Issue removes), never from the sign of the quantity — a negative 'Receipt' would quietly subtract stock while reading as an addition.", max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
