# Generated by Django 4.2.30 on 2026-07-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('inventory', '0003_alter_stockentry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='item',
            field=models.ForeignKey(help_text='PROTECT: an item with stock movements cannot be deleted — its StockEntry rows are the audit trail of every receipt and issue.', on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='warehouse',
            field=models.ForeignKey(help_text='PROTECT: a warehouse with stock movements cannot be deleted — its StockEntry rows are the record of everything that moved through it, and a movement with no warehouse is meaningless.', on_delete=django.db.models.deletion.PROTECT, to='core.warehouse'),
        ),
    ]
