# Generated by Django 4.2.30 on 2026-07-19 02:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockentry_item_alter_stockentry_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembatch',
            name='potency',
            field=models.DecimalField(decimal_places=4, default=Decimal('100.0000'), help_text='Measured active strength of this batch, as % of nominal (100 = exactly nominal). Used for potency-adjusted consumption.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
