# Generated by Django 4.2.30 on 2026-07-17 20:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockentry_bin_location'),
        ('hr', '0003_employee_probation_reviewed_at_and_more'),
        ('core', '0006_binlocation_and_more'),
        ('buying', '0004_goodsreceipt_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField()),
                ('required_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Ordered', 'Ordered'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_approved', to='hr.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='core.companyprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_raised', to='hr.employee')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_end',
            field=models.DateField(blank=True, help_text='PRC-RULE-005: alerted for renewal 60 days before this date.', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text="Estimated unit price. Falls back to the item's standard rate.", max_digits=18, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='inventory.item')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Set once this line has been carried onto a PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_lines', to='buying.purchaseorder')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buying.purchaserequisition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
