# Generated by Django 4.2.30 on 2026-07-18 01:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_leaveentitlement_hrpolicy_endofservicepolicy_and_more'),
        ('core', '0007_cyclecount_cyclecountline'),
        ('buying', '0005_purchaserequisition_supplier_contract_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierScorecardCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Relative weight. Scores are normalised by the total weight, so these need not sum to 100.', max_digits=6)),
                ('max_score', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_criteria', to='core.companyprofile')),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_evaluations', to='hr.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='buying.supplier')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='buying.supplierscorecardcriterion')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='buying.supplierscorecard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LatePenaltyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_per_day', models.DecimalField(decimal_places=3, help_text='Percent of order value charged per day late.', max_digits=6)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('max_percent', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Cap on the total penalty, as a percent of order value.', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_penalty_terms', to='core.companyprofile')),
                ('supplier', models.ForeignKey(blank=True, help_text='Blank makes this the company-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_terms', to='buying.supplier')),
            ],
            options={
                'ordering': ['-supplier_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierscorecardcriterion',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_scorecard_criterion_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplierscore',
            constraint=models.UniqueConstraint(fields=('scorecard', 'criterion'), name='unique_score_per_criterion'),
        ),
    ]
