# Generated by Django 4.2.30 on 2026-07-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0006_supplierscorecardcriterion_supplierscorecard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='PROTECT: a supplier with purchase orders cannot be deleted — the orders are procurement history.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='buying.supplier'),
        ),
    ]
