# Generated by Django 4.2.30 on 2026-07-18 17:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('inventory', '0004_alter_stockentry_item_alter_stockentry_warehouse'),
        ('buying', '0007_alter_purchaseorder_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField()),
                ('response_deadline', models.DateField(blank=True, help_text='Date by which suppliers should return their quotes.', null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Quoted', 'Quoted'), ('Awarded', 'Awarded'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='core.companyprofile')),
                ('requisition', models.ForeignKey(blank=True, help_text='The requisition this RFQ sources, if it came from one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='buying.purchaserequisition')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('target_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional expected/target price, for reference only.', max_digits=18, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='inventory.item')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buying.rfq')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=100)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Days from order to delivery the supplier promises.', null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Awarded', 'Awarded'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='buying.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='buying.supplier')),
            ],
            options={
                'ordering': ['rfq', 'id'],
                'unique_together': {('rfq', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text="This supplier's unit price for the RFQ line.", max_digits=18, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='buying.supplierquotation')),
                ('rfq_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='buying.rfqitem')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('quotation', 'rfq_line')},
            },
        ),
    ]
