# Generated by Django 4.2.30 on 2026-07-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="posted_to_ledger",
            field=models.BooleanField(
                default=False,
                help_text="Whether this payroll's salary expense has been posted to the GL.",
            ),
        ),
    ]
