# Generated by Django 4.2.30 on 2026-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_payroll_posted_to_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='probation_reviewed_at',
            field=models.DateField(blank=True, help_text='HR-RULE-002: set when the probation review is completed. While null and the 90-day window has passed, the employee is flagged.', null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='base_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HR-RULE-004: ordinary hourly wage. Overtime multipliers apply on top of this, so it must be the plain rate, not a pre-multiplied one.', max_digits=18),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_holiday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HR-RULE-004: weekend/holiday overtime, paid at 2x base_hourly_rate.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_weekday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HR-RULE-004: paid at 1.5x base_hourly_rate.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy flat-rate overtime hours, paid at overtime_rate with no multiplier. Superseded by the weekday/holiday split below.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy flat overtime rate per hour.', max_digits=18),
        ),
    ]
