# Generated by Django 4.2.30 on 2026-07-17 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_employee_probation_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approved_by_dept_head',
            field=models.ForeignKey(blank=True, help_text='HR-CTRL-002: department head sign-off on this hire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hires_approved_as_dept_head', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='approved_by_hr',
            field=models.ForeignKey(blank=True, help_text='HR-CTRL-002: HR sign-off. Both are required before the employee can be made Active.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hires_approved_as_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField()),
                ('reason', models.CharField(choices=[('Resignation', 'Resignation'), ('End of Contract', 'End of Contract'), ('Redundancy', 'Redundancy'), ('Dismissal', 'Dismissal'), ('Retirement', 'Retirement'), ('Other', 'Other')], max_length=50)),
                ('reason_detail', models.TextField(blank=True, help_text='Free-text narrative behind the reason code.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminations_approved_as_hr', to=settings.AUTH_USER_MODEL)),
                ('approved_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminations_approved_as_manager', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='hr.employee')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminations_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-termination_date', '-id'],
            },
        ),
    ]
