# Generated by Django 4.2.30 on 2026-07-18 01:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('hr', '0004_employee_approved_by_dept_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(blank=True, help_text='Blank means it applies to every employment type.', max_length=50)),
                ('min_tenure_years', models.PositiveIntegerField(default=0, help_text='Applies once the employee has served this many years.')),
                ('days_per_year', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='core.companyprofile')),
            ],
            options={
                'ordering': ['-min_tenure_years', 'employment_type'],
            },
        ),
        migrations.CreateModel(
            name='HRPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probation_days', models.PositiveIntegerField(default=90)),
                ('overtime_weekday_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=5)),
                ('overtime_holiday_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5)),
                ('default_annual_leave_days', models.PositiveIntegerField(default=21, help_text='Used when no LeaveEntitlement rule matches the employee.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_policy', to='core.companyprofile')),
            ],
            options={
                'verbose_name_plural': 'HR policies',
            },
        ),
        migrations.CreateModel(
            name='EndOfServicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage_basis', models.CharField(choices=[('basic', 'Basic salary'), ('gross', 'Gross salary')], default='basic', help_text='Which wage the per-year fraction applies to.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eosb_policy', to='core.companyprofile')),
            ],
            options={
                'verbose_name_plural': 'End of service policies',
            },
        ),
        migrations.CreateModel(
            name='EndOfServiceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_years', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('to_years', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for 'and above'.", max_digits=5, null=True)),
                ('months_per_year', models.DecimalField(decimal_places=3, help_text='Months of wage accrued per year of service inside this band.', max_digits=5)),
                ('resignation_fraction', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text="Multiplier applied to this band's entitlement when the employee resigns. 1 means resignation is treated the same as termination.", max_digits=5)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='hr.endofservicepolicy')),
            ],
            options={
                'ordering': ['from_years'],
            },
        ),
        migrations.AddConstraint(
            model_name='leaveentitlement',
            constraint=models.UniqueConstraint(fields=('company', 'employment_type', 'min_tenure_years'), name='unique_leave_entitlement_rule'),
        ),
    ]
