# Generated by Django 4.2.30 on 2026-07-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=200)),
                ("date", models.DateField(db_index=True)),
                ("project", models.CharField(blank=True, max_length=200)),
                ("task", models.CharField(blank=True, max_length=200)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("billable", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "timesheets",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_no", models.CharField(blank=True, max_length=50)),
                ("employee_name", models.CharField(max_length=200)),
                ("date", models.DateField(db_index=True)),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("leave", "On Leave"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "attendance",
                "ordering": ["-date", "employee_name"],
                "unique_together": {("employee_no", "date")},
            },
        ),
    ]
