# Generated by Django 4.2.30 on 2026-07-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pmo", "0003_project_actual_end_date_project_actual_start_date_and_more"),
        ("hr", "0002_payroll_posted_to_ledger"),
        ("attendance", "0002_attendance_tenant_timesheet_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable for backward compatibility with rows recorded before this field existed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable for backward compatibility with rows recorded before this field existed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="project_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets",
                to="pmo.project",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="task_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets",
                to="pmo.task",
            ),
        ),
    ]
