[pytest]
DJANGO_SETTINGS_MODULE = nexus.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --color=yes
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
testpaths = tests
