# Generated by Django 4.2.30 on 2026-07-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("name_ar", models.CharField(blank=True, max_length=150)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "All Items"),
                            ("item", "Specific Item"),
                            ("category", "Category"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=120)),
                (
                    "min_quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage"),
                            ("fixed_amount", "Fixed Amount Off"),
                            ("fixed_price", "Fixed Price"),
                        ],
                        default="percent",
                        max_length=12,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_rules",
                "ordering": ["-priority", "name"],
            },
        ),
    ]
