# Generated by Django 4.2.30 on 2026-07-05 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('commercial_registration', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Saudi Arabia', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('default_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=10)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('fiscal_year_end', models.DateField(blank=True, null=True)),
                ('time_zone', models.CharField(default='Asia/Riyadh', max_length=50)),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=20)),
                ('number_format', models.CharField(default='#,###.##', max_length=20)),
                ('a4_top_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('a4_bottom_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('a4_left_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('a4_right_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('page_header', models.TextField(blank=True)),
                ('page_footer', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('social_media_links', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Sales Order', 'Sales Order'), ('Invoice', 'Invoice'), ('Payslip', 'Payslip'), ('Journal Entry', 'Journal Entry')], max_length=50)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('Letter', 'Letter')], default='A4', max_length=20)),
                ('orientation', models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], default='Portrait', max_length=20)),
                ('top_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('bottom_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('left_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('right_margin', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('header', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=False)),
                ('show_stamp', models.BooleanField(default=False)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('font_size', models.PositiveIntegerField(default=12)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('User', 'User'), ('Accountant', 'Accountant')], default='User', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, help_text='Tenant this login belongs to. Left null only for superusers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
