# Generated by Django 4.2.30 on 2026-07-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('Head Office', 'Head Office'), ('Branch', 'Branch'), ('Warehouse', 'Warehouse'), ('Showroom', 'Showroom')], default='Branch', help_text='BRN-RULE-002: only one Head Office is allowed per company.', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='license_expiry',
            field=models.DateField(blank=True, help_text='BRN-CTRL-005: commercial license expiry, alerted on 60 days ahead.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
