# Generated by Django 4.2.30 on 2026-07-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('core', '0005_branch_branch_type_branch_close_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('aisle', models.CharField(blank=True, max_length=50)),
                ('rack', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Units this bin holds. 0 means unconstrained.')),
                ('pick_sequence', models.PositiveIntegerField(default=0, help_text='WHS-RULE-002: traversal order for wave picking — lower is reached first on the walk route.')),
                ('is_active', models.BooleanField(default=True)),
                ('item_group', models.ForeignKey(blank=True, help_text="WHS-RULE-001: putaway prefers a bin dedicated to the item's group.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='inventory.itemgroup')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='core.warehouse')),
            ],
            options={
                'db_table': 'core_bin_locations',
                'ordering': ['warehouse', 'pick_sequence', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='binlocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_bin_code_per_warehouse'),
        ),
    ]
