# Generated by Django 4.2.30 on 2026-07-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_probation_reviewed_at_and_more'),
        ('inventory', '0002_stockentry_bin_location'),
        ('core', '0006_binlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Counted', 'Counted'), ('Reconciled', 'Reconciled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts', to='hr.employee')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='core.warehouse')),
            ],
            options={
                'db_table': 'core_cycle_counts',
                'ordering': ['-scheduled_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=2, default=0, help_text='What the system believed at the moment the count was drawn.', max_digits=18)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Null until someone actually counts it.', max_digits=18, null=True)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.cyclecount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'db_table': 'core_cycle_count_lines',
                'ordering': ['id'],
            },
        ),
    ]
