# Generated by Django 4.2.7 on 2026-07-20 10:49

from django.db import migrations, models
import nexus.apps.sales.models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_backorder_quantity_pending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(default=nexus.apps.sales.models.today),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_date",
            field=models.DateField(default=nexus.apps.sales.models.today),
        ),
    ]
