# Generated by Django 4.2.30 on 2026-07-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="translation",
            name="unique_translation_lang_key_ctx",
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="i18n_transl_key_f8c286_idx",
            old_name="i18n_transla_key_7f8b8c_idx",
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="i18n_transl_context_fd4742_idx",
            old_name="i18n_transla_conte_3a2b1c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("language", "key", "context")},
        ),
    ]
