# Generated by Django 4.2.7 on 2026-07-19 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
