# Generated by Django 4.2.30 on 2026-07-17 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buying", "0003_purchaseorder_billed_amount_and_more"),
        ("core", "0004_user_tenant"),
        ("inventory", "0001_initial"),
        ("hr", "0002_payroll_posted_to_ledger"),
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("Incoming", "Incoming"),
                            ("In Process", "In Process"),
                            ("Final", "Final"),
                            ("Outgoing", "Outgoing"),
                        ],
                        default="Incoming",
                        max_length=20,
                    ),
                ),
                (
                    "sample_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("inspection_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_inspections",
                        to="core.companyprofile",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections",
                        to="hr.employee",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_inspections",
                        to="inventory.item",
                    ),
                ),
                (
                    "reference_purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections",
                        to="buying.purchaseorder",
                    ),
                ),
                (
                    "reference_work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QualityInspectionParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.CharField(max_length=255)),
                ("specification", models.CharField(blank=True, max_length=255)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "reading_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Accepted", "Accepted"), ("Rejected", "Rejected")],
                        default="Accepted",
                        max_length=10,
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="manufacturing.qualityinspection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=255)),
                ("workstation", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Work In Progress", "Work In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "for_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "completed_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("started_time", models.DateTimeField(blank=True, null=True)),
                ("ended_time", models.DateTimeField(blank=True, null=True)),
                (
                    "hour_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actual_operating_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=18
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_cards",
                        to="core.companyprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_cards",
                        to="hr.employee",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_cards",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
