# Generated by Django 4.2.30 on 2026-07-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_payroll_posted_to_ledger'),
        ('core', '0006_binlocation_and_more'),
        ('inventory', '0002_stockentry_bin_location'),
        ('manufacturing', '0002_qualityinspection_qualityinspectionparameter_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='MFG-CTRL-001: a BOM must be approved before production releases against it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boms', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scrap_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='MFG-RULE-005: units lost in production. Their cost is absorbed by the good units, raising the effective unit cost.', max_digits=18),
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_reservations', to='core.warehouse')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='manufacturing.workorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
