# Generated by Django 4.2.30 on 2026-07-18 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('hr', '0004_employee_approved_by_dept_head_and_more'),
        ('manufacturing', '0003_bom_approved_at_bom_approved_by_workorder_scrap_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=0, help_text='MFG-CTRL-005: days between preventive services. 0 means no schedule, and is not enforced.')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='core.companyprofile')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to='hr.employee')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='manufacturing.workstation')),
            ],
            options={
                'ordering': ['-performed_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='workstation_ref',
            field=models.ForeignKey(blank=True, help_text='MFG-CTRL-005: the machine this order runs on. Optional — the free-text `workstation` field predates this and still works.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='manufacturing.workstation'),
        ),
        migrations.AddConstraint(
            model_name='workstation',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_workstation_code_per_company'),
        ),
    ]
