# Generated by Django 4.2.30 on 2026-07-19 02:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itembatch_potency'),
        ('core', '0007_cyclecount_cyclecountline'),
        ('manufacturing', '0004_workstation_maintenancelog_workorder_workstation_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='is_potency_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_batch_no', models.CharField(max_length=100)),
                ('output_qty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('output_potency', models.DecimalField(blank=True, decimal_places=4, help_text='Assayed strength of the finished batch, as % of nominal.', max_digits=7, null=True)),
                ('manufactured_on', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='core.companyprofile')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='manufacturing.workorder')),
            ],
            options={
                'ordering': ['-manufactured_on', '-id'],
                'unique_together': {('output_item', 'output_batch_no')},
            },
        ),
        migrations.CreateModel(
            name='BatchConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_batch_no', models.CharField(max_length=100)),
                ('nominal_qty', models.DecimalField(decimal_places=4, help_text='The recipe quantity before any potency adjustment.', max_digits=18)),
                ('actual_qty', models.DecimalField(decimal_places=4, help_text='The physical quantity drawn, after potency adjustment.', max_digits=18)),
                ('batch_potency', models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=7)),
                ('input_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='manufacturing.productionbatch')),
            ],
            options={
                'ordering': ['production_batch', 'id'],
            },
        ),
    ]
