# Generated by Django 4.2.30 on 2026-07-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('manufacturing', '0005_bomitem_is_potency_managed_productionbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='core.companyprofile')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='manufacturing.workorder')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='manufacturing.workstation')),
            ],
            options={
                'ordering': ['workstation', 'start'],
                'indexes': [models.Index(fields=['workstation', 'start', 'end'], name='manufacturi_worksta_dae29b_idx')],
            },
        ),
    ]
