# Generated by Django 5.1.15 on 2026-07-08 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(blank=True, max_length=20, unique=True)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employees', models.PositiveIntegerField(default=0)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'industry_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('sustainability', 'Sustainability'), ('innovation', 'Innovation')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(help_text='e.g. Q1-2026, FY2025', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='industry.company')),
            ],
            options={
                'db_table': 'industry_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sectors', to='industry.sector')),
            ],
            options={
                'db_table': 'industry_sectors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='industry.sector'),
        ),
    ]
