# Generated by Django 5.1.15 on 2026-07-09 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vertical_type', models.CharField(choices=[('general_business', 'General Business'), ('aviation_aerospace', 'Aviation & Aerospace'), ('healthcare_medical', 'Healthcare & Medical'), ('banking_finance', 'Banking & Finance'), ('hospitality_tourism', 'Hospitality & Tourism'), ('government_public', 'Government & Public Sector'), ('energy_utilities', 'Energy & Utilities'), ('education_training', 'Education & Training'), ('manufacturing', 'Manufacturing'), ('retail_ecommerce', 'Retail & E-commerce'), ('real_estate', 'Real Estate'), ('logistics_transportation', 'Logistics & Transportation')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_modules', models.JSONField(default=list)),
                ('default_features', models.JSONField(default=dict)),
                ('default_reports', models.JSONField(default=list)),
                ('default_compliance', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'industry_vertical_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryVertical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('modules_enabled', models.JSONField(default=list, help_text="List of module codes enabled: ['core', 'pmo', 'industry', 'ai_module', 'regulatory']")),
                ('features_config', models.JSONField(default=dict, help_text="Feature flags per module: {'pmo': ['projects', 'tasks'], 'ai_module': ['predictions']}")),
                ('report_templates', models.JSONField(default=list, help_text='Available report templates for this vertical')),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('supported_currencies', models.JSONField(default=list)),
                ('multi_branch_enabled', models.BooleanField(default=False)),
                ('multi_warehouse_enabled', models.BooleanField(default=False)),
                ('compliance_frameworks', models.JSONField(default=list, help_text="e.g. ['ISO9001', 'GDPR', 'HIPAA']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verticals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Industry Vertical',
                'verbose_name_plural': 'Industry Verticals',
                'db_table': 'industry_verticals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(blank=True, max_length=20, unique=True)),
                ('custom_modules', models.JSONField(blank=True, default=list, help_text="Additional modules beyond the vertical's default")),
                ('custom_features', models.JSONField(blank=True, default=dict, help_text="Additional features beyond the vertical's default")),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employees', models.PositiveIntegerField(default=0)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('multi_branch_enabled', models.BooleanField(default=False)),
                ('multi_warehouse_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry_vertical', models.ForeignKey(help_text='The Industry Vertical that controls this company', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='industry.industryvertical')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'industry_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('sustainability', 'Sustainability'), ('innovation', 'Innovation'), ('compliance', 'Compliance')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(help_text='e.g. Q1-2026, FY2025', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='industry.company')),
            ],
            options={
                'db_table': 'industry_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry_vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='industry.industryvertical')),
                ('parent_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sectors', to='industry.sector')),
            ],
            options={
                'db_table': 'industry_sectors',
                'ordering': ['industry_vertical__name', 'name'],
                'unique_together': {('industry_vertical', 'code')},
            },
        ),
    ]
