# Generated by Django 4.2.30 on 2026-07-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="industry.sector",
            ),
        ),
    ]
