# Generated by Django 5.1.15 on 2026-07-08 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nlp', 'NLP'), ('cv', 'Computer Vision'), ('forecasting', 'Forecasting'), ('anomaly', 'Anomaly Detection')], max_length=20)),
                ('status', models.CharField(choices=[('training', 'Training'), ('ready', 'Ready'), ('deployed', 'Deployed'), ('deprecated', 'Deprecated')], default='training', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('f1_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('training_data_size', models.PositiveBigIntegerField(default=0)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
