# Generated by Django 5.1.15 on 2026-07-09 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_module', '0001_initial'),
        ('pmo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insight',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to='pmo.project'),
        ),
        migrations.AddField(
            model_name='insight',
            name='source_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='ai_module.aimodel'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_module.aimodel'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('name', 'version')},
        ),
    ]
