# Generated by Django 4.2.30 on 2026-07-19 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('operation', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('user_email', models.CharField(blank=True, max_length=254)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_document',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChangeDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.changedocument')),
            ],
            options={
                'db_table': 'change_document_item',
                'ordering': ['document', 'field_name'],
                'indexes': [models.Index(fields=['field_name'], name='change_docu_field_n_e5374b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='changedocument',
            index=models.Index(fields=['content_type', 'object_id'], name='change_docu_content_8574d7_idx'),
        ),
    ]
