# Generated by Django 4.2.30 on 2026-07-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name_ar", models.CharField(max_length=80)),
                ("symbol", models.CharField(blank=True, max_length=12)),
                ("category", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "units_of_measure",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="UOMConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor", models.DecimalField(decimal_places=6, max_digits=16)),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_from",
                        to="uom.unitofmeasure",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_to",
                        to="uom.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "uom_conversions",
            },
        ),
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_code", models.CharField(db_index=True, max_length=50)),
                ("template_name", models.CharField(blank=True, max_length=200)),
                ("sku", models.CharField(max_length=80)),
                ("attributes", models.JSONField(default=dict)),
                (
                    "extra_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "item_variants",
                "ordering": ["template_code", "sku"],
            },
        ),
    ]
