# Generated by Django 4.2.7 on 2026-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="reserved_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
