# Generated by Django 4.2.30 on 2026-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradeDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("quotation", "Quotation"),
                            ("delivery", "Delivery Note"),
                            ("receipt", "Goods Receipt"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("number", models.CharField(max_length=50, unique=True)),
                ("party_name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("item_code", models.CharField(blank=True, max_length=50)),
                ("item_name", models.CharField(blank=True, max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("warehouse", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("converted", "Converted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("linked_ref", models.CharField(blank=True, max_length=80)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trade_documents",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
