# Generated by Django 5.1.15 on 2026-07-09 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under Review'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('effective_date', models.DateField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('document_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_regulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulatory_regulations',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('likelihood', models.PositiveSmallIntegerField(choices=[(1, 'Rare'), (2, 'Unlikely'), (3, 'Possible'), (4, 'Likely'), (5, 'Almost Certain')])),
                ('impact', models.PositiveSmallIntegerField(choices=[(1, 'Negligible'), (2, 'Minor'), (3, 'Moderate'), (4, 'Major'), (5, 'Catastrophic')])),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('related_regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='regulatory.regulation')),
            ],
            options={
                'db_table': 'regulatory_risks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('findings', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_checks', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='core.branch')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='regulatory.regulation')),
            ],
            options={
                'db_table': 'regulatory_compliance_checks',
                'ordering': ['-checked_at'],
                'unique_together': {('regulation', 'branch')},
            },
        ),
    ]
