# Generated by Django 4.2.30 on 2026-07-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_tenant_budget_tenant_costcenter_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="is_reversed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="accounts.journalentry",
            ),
        ),
    ]
