# Generated by Django 4.2.30 on 2026-07-17 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_accountingperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='First approver. FIN-CTRL-001 requires one above 50,000 SAR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='second_approved_by',
            field=models.ForeignKey(blank=True, help_text='Second, distinct approver required above 50,000 SAR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_second_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
