# Generated by Django 4.2.30 on 2026-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_journalentry_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='posted',
            field=models.BooleanField(default=False, help_text='True once this entry has hit the ledger. Guards against double-posting: nothing depends on the caller only ever calling once.'),
        ),
    ]
