# Generated by Django 4.2.30 on 2026-07-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_journalentry_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(help_text='PROTECT: an account carrying posted journal lines cannot be deleted — doing so would erase ledger history and unbalance the entries that reference it.', on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounts.account'),
        ),
    ]
