# Generated by Django 4.2.30 on 2026-07-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('tenants', '0002_tenant_database_url'),
        ('accounts', '0007_alter_journalentryline_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('standard', models.CharField(choices=[('ifrs', 'IFRS'), ('local_gaap', 'Local GAAP (SOCPA)'), ('tax', 'Tax'), ('management', 'Management')], max_length=16)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('is_leading', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='core.companyprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['company', '-is_leading', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('posting_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.account')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_postings', to='accounts.journalentry')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='accounts.ledger')),
            ],
            options={
                'ordering': ['ledger', 'posting_date', 'id'],
                'indexes': [models.Index(fields=['ledger', 'account'], name='accounts_le_ledger__d42197_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_ledger_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(condition=models.Q(('is_leading', True)), fields=('company',), name='one_leading_ledger_per_company'),
        ),
    ]
