# Generated by Django 4.2.30 on 2026-07-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customfields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='formula',
            field=models.TextField(blank=True, help_text="Expression using {field_key} references, e.g. '{qty} * {price}'. Only + - * / ( ) and numbers are allowed — no code."),
        ),
        migrations.AddField(
            model_name='customfield',
            name='lookup_match_local',
            field=models.CharField(blank=True, help_text='Field on THIS record whose value we match on.', max_length=60),
        ),
        migrations.AddField(
            model_name='customfield',
            name='lookup_match_source',
            field=models.CharField(blank=True, help_text='Field on the source row that must equal the local value.', max_length=60),
        ),
        migrations.AddField(
            model_name='customfield',
            name='lookup_module',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='customfield',
            name='lookup_return',
            field=models.CharField(blank=True, help_text='Field on the matched source row to return.', max_length=60),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('boolean', 'Boolean'), ('textarea', 'Text Area'), ('formula', 'Formula'), ('lookup', 'Lookup')], default='text', max_length=12),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=64)),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='customfields.customfield')),
            ],
            options={
                'db_table': 'custom_field_values',
                'indexes': [models.Index(fields=['field', 'record_id'], name='custom_fiel_field_i_970fca_idx')],
                'unique_together': {('field', 'record_id')},
            },
        ),
    ]
