# Generated by Django 4.2.30 on 2026-07-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('customfields', '0002_customfield_formula_customfield_lookup_match_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=60)),
                ('control_key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('label_ar', models.CharField(blank=True, max_length=120)),
                ('layout', models.CharField(choices=[('section', 'Section'), ('table', 'Repeating table')], default='section', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_module', models.CharField(blank=True, help_text='If set, a table control reads its rows from this module instead of storing its own.', max_length=60)),
                ('linked_match_local', models.CharField(blank=True, help_text='Field on THIS record used to match linked rows.', max_length=60)),
                ('linked_match_source', models.CharField(blank=True, help_text='Field on the linked row that must equal the local value.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'custom_controls',
                'ordering': ['module', 'order', 'id'],
                'unique_together': {('tenant', 'module', 'control_key')},
            },
        ),
        migrations.AddField(
            model_name='customfield',
            name='control',
            field=models.ForeignKey(blank=True, help_text='The control (section/table) this field belongs to. Null means it sits directly on the module form, as before.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='customfields.customcontrol'),
        ),
    ]
