# Generated by Django 4.2.30 on 2026-07-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customfields', '0003_customcontrol_customfield_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomControlRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=64)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='customfields.customcontrol')),
            ],
            options={
                'db_table': 'custom_control_rows',
                'ordering': ['control', 'record_id', 'row_index'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='row',
            field=models.ForeignKey(blank=True, help_text='Set when this value belongs to a row of a repeating control; null for a plain field or a section field.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='customfields.customcontrolrow'),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('field', 'record_id', 'row')},
        ),
        migrations.AddIndex(
            model_name='customcontrolrow',
            index=models.Index(fields=['control', 'record_id'], name='custom_cont_control_fcb1dc_idx'),
        ),
    ]
