# Generated by Django 4.2.30 on 2026-07-16 14:39

import apps.automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="target_url",
            field=models.URLField(
                max_length=500,
                validators=[apps.automation.models.validate_webhook_target_url],
            ),
        ),
    ]
