# Generated by Django 4.2.30 on 2026-07-19 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('automation', '0002_alter_webhook_target_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model_label', models.CharField(db_index=True, help_text="Which model this watches, as 'app_label.ModelName'.", max_length=80)),
                ('trigger', models.CharField(choices=[('on_create', 'On create'), ('on_update', 'On update'), ('on_create_or_update', 'On create or update')], default='on_create', max_length=20)),
                ('condition_field', models.CharField(blank=True, max_length=60)),
                ('condition_operator', models.CharField(blank=True, help_text='One of ==, !=, >, >=, <, <=.', max_length=4)),
                ('condition_value', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'automated_actions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedActionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('step_type', models.CharField(choices=[('set_field', 'Set a field'), ('notify', 'Create a notification'), ('webhook', 'Fire a webhook')], max_length=10)),
                ('target_field', models.CharField(blank=True, max_length=60)),
                ('target_value', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.automatedaction')),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.webhook')),
            ],
            options={
                'db_table': 'automated_action_steps',
                'ordering': ['action', 'order'],
            },
        ),
    ]
