# Generated by Django 4.2.30 on 2026-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("name", models.CharField(max_length=200)),
                ("responsibility", models.TextField(blank=True)),
                ("database_entity", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "controls_ai_agents",
                "ordering": ["industry", "name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Industries",
                "db_table": "controls_industries",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="IndustryControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(db_index=True, max_length=200)),
                ("module", models.CharField(blank=True, max_length=200)),
                ("control_id", models.CharField(max_length=60, unique=True)),
                ("control_name", models.CharField(max_length=200)),
                ("sub_control", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("required", models.BooleanField(default=True)),
                ("ai_agent", models.CharField(blank=True, max_length=200)),
                ("database_entity", models.CharField(blank=True, max_length=200)),
                ("kpi", models.CharField(blank=True, max_length=200)),
                ("compliance", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "controls_industry_controls",
                "ordering": ["industry", "module", "control_id"],
            },
        ),
        migrations.CreateModel(
            name="MasterEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("usage", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Master entities",
                "db_table": "controls_master_entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FormControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(default=0)),
                ("form_name", models.CharField(db_index=True, max_length=200)),
                ("input_name", models.CharField(max_length=255)),
                ("input_type", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("missing", "Missing"),
                            ("planned", "Planned"),
                        ],
                        db_index=True,
                        default="missing",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        db_index=True,
                        default="Medium",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "controls_form_controls",
                "ordering": ["form_name", "seq"],
                "unique_together": {("form_name", "input_name")},
            },
        ),
    ]
