# Generated by Django 4.2.30 on 2026-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("company_code", models.CharField(max_length=30, unique=True)),
                ("sector", models.CharField(blank=True, db_index=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=150)),
                ("sub_industry", models.CharField(blank=True, max_length=150)),
                ("company_type", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(default="SAR", max_length=10)),
                ("language", models.CharField(default="Arabic", max_length=30)),
                ("timezone", models.CharField(default="Asia/Riyadh", max_length=50)),
                ("fiscal_year", models.CharField(blank=True, max_length=30)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                (
                    "commercial_registration",
                    models.CharField(blank=True, max_length=50),
                ),
                ("enabled_modules", models.JSONField(blank=True, default=list)),
                ("departments", models.JSONField(blank=True, default=list)),
                ("enabled_entities", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "controls_company_setup",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SectorControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector", models.CharField(db_index=True, max_length=100)),
                ("entity", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("fields", models.JSONField(blank=True, default=list)),
                ("module", models.CharField(blank=True, max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_core", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "controls_sector_controls",
                "ordering": ["sector", "order", "entity"],
                "unique_together": {("sector", "entity")},
            },
        ),
    ]
