# Generated by Django 4.2.30 on 2026-07-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountingperiod'),
        ('pmo', '0003_project_actual_end_date_project_actual_start_date_and_more'),
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of invoice totals generated from this order. Maintained by Invoice.create_from_sales_order().', max_digits=18),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='accounts.costcenter'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='pmo.project'),
        ),
    ]
