# Generated by Django 4.2.30 on 2026-07-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_payroll_posted_to_ledger'),
        ('selling', '0002_salesorder_billed_amount_salesorder_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who authorised a discount above 10% (SAL-CTRL-004).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_discounts', to='hr.employee'),
        ),
    ]
