# Generated by Django 4.2.30 on 2026-07-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_binlocation_and_more'),
        ('inventory', '0002_stockentry_bin_location'),
        ('selling', '0003_salesorder_discount_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='backorder_of',
            field=models.ForeignKey(blank=True, help_text='SAL-RULE-004: set when this order carries quantities that the original order could not fulfil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='selling.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='backordered_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SAL-RULE-004: quantity moved onto a backorder because stock was short at confirmation.', max_digits=18),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reservations', to='inventory.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='selling.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reservations', to='core.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
