# Generated by Django 4.2.30 on 2026-07-18 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selling', '0004_salesorder_backorder_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_processing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='data_processing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='CRM-CTRL-005: explicit opt-in. Defaults to False — consent that was never given cannot be assumed.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('marketing', 'Marketing'), ('data_processing', 'Data Processing')], max_length=50)),
                ('granted', models.BooleanField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_changes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='selling.customer')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
