# Generated by Django 4.2.30 on 2026-07-18 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_leaveentitlement_hrpolicy_endofservicepolicy_and_more'),
        ('core', '0007_cyclecount_cyclecountline'),
        ('selling', '0005_customer_data_processing_consent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_annual_revenue', models.DecimalField(decimal_places=2, help_text='Revenue over the trailing window at or above which this tier applies.', max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Standing discount this tier earns. Informational — SAL-CTRL-004 still governs what needs approval.', max_digits=5)),
                ('window_months', models.PositiveIntegerField(default=12, help_text="How far back 'annual' reaches for this tier.")),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tiers', to='core.companyprofile')),
            ],
            options={
                'ordering': ['-min_annual_revenue'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Orders below this earn nothing under this rule.', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='core.companyprofile')),
                ('sales_person', models.ForeignKey(blank=True, help_text='Blank means the rule applies to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='hr.employee')),
                ('tier', models.ForeignKey(blank=True, help_text='Blank means it applies regardless of customer tier.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='selling.customertier')),
            ],
            options={
                'ordering': ['-min_order_value'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='SAL-RULE-005: maintained by recalculate_tier().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='selling.customertier'),
        ),
        migrations.AddConstraint(
            model_name='customertier',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_customer_tier_per_company'),
        ),
    ]
