# Generated by Django 4.2.30 on 2026-07-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockentry_item_alter_stockentry_warehouse'),
        ('selling', '0006_customertier_commissionrule_customer_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(help_text='PROTECT: a customer with sales orders cannot be deleted — the orders are a business record of the relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='selling.customer'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='item',
            field=models.ForeignKey(help_text='PROTECT: an item that appears on a sales order line cannot be deleted — the order is a business record of what was sold.', on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
    ]
