# Generated by Django 4.2.7 on 2026-07-19 20:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_primary", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "customer_name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company"),
                            ("government", "Government"),
                        ],
                        default="company",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?[0-9\\-\\s()]{7,20}$",
                            )
                        ],
                    ),
                ),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("net_15", "Net 15"),
                            ("net_30", "Net 30"),
                            ("net_60", "Net 60"),
                            ("net_90", "Net 90"),
                            ("cod", "COD"),
                            ("prepaid", "Prepaid"),
                        ],
                        default="net_30",
                        max_length=20,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("campaign", "Campaign"),
                            ("trade_show", "Trade Show"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("prospect", "Prospect"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                (
                    "lead_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("qualification", "Qualification"),
                            ("needs_analysis", "Needs Analysis"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="qualification",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("probability", models.PositiveSmallIntegerField(default=10)),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
