# Generated by Django 4.2.30 on 2026-07-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="opportunity",
            options={"ordering": ["-created_at"]},
        ),
    ]
