# Generated by Django 4.2.30 on 2026-07-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cyclecount_cyclecountline'),
        ('crm', '0002_alter_lead_options_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='CRM-RULE-001: maintained by recalculate_score().'),
        ),
        migrations.CreateModel(
            name='LeadScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_name', models.CharField(help_text="Which Lead field this rule inspects, e.g. 'source', 'email'.", max_length=50)),
                ('match_type', models.CharField(choices=[('equals', 'Equals'), ('not_empty', 'Is filled in'), ('contains', 'Contains')], default='not_empty', max_length=20)),
                ('match_value', models.CharField(blank=True, help_text="The value to compare against. Unused for 'is filled in'.", max_length=255)),
                ('points', models.IntegerField(help_text='Points awarded when the rule matches. Negative is allowed.')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_scoring_rules', to='core.companyprofile')),
            ],
            options={
                'ordering': ['-points', 'name'],
            },
        ),
    ]
