# Generated by Django 4.2.7 on 2026-07-19 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=50)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("I", "Insert"), ("U", "Update"), ("D", "Delete")],
                        max_length=1,
                    ),
                ),
                (
                    "username_snapshot",
                    models.CharField(default="system", max_length=150),
                ),
                ("change_time", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Header (CDHDR)",
                "ordering": ["-change_time"],
            },
        ),
        migrations.CreateModel(
            name="ChangeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "change_indicator",
                    models.CharField(
                        choices=[("I", "Insert"), ("U", "Update"), ("D", "Delete")],
                        max_length=1,
                    ),
                ),
                ("value_old", models.TextField(blank=True)),
                ("value_new", models.TextField(blank=True)),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="audit.changeheader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Item (CDPOS)",
            },
        ),
        migrations.AddIndex(
            model_name="changeheader",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_chang_content_3c0a07_idx",
            ),
        ),
    ]
