# Generated by Django 4.2.30 on 2026-07-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='database_url',
            field=models.CharField(blank=True, help_text="If set, this tenant's own database (e.g. postgres://…). Blank means the shared default database.", max_length=500),
        ),
    ]
