# Generated by Django 4.2.30 on 2026-07-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pmo", "0002_alter_milestone_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="actual_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Actual End Date"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="actual_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Actual Start Date"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="pmo.milestone",
                verbose_name="Milestone",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="pmo.task",
                verbose_name="Parent Task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="progress",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Auto-computed from task completion ratio once the project has tasks (see recalculate_progress); stays manually editable for projects with no tasks yet.",
                verbose_name="Progress %",
            ),
        ),
    ]
