# Generated by Django 4.2.30 on 2026-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0003_project_actual_end_date_project_actual_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='PRJ-RULE-003: working span used by the critical path calculation.'),
        ),
        migrations.AddField(
            model_name='task',
            name='early_finish',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='early_start',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_critical',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='late_finish',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='late_start',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='predecessors',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must finish before this one starts (finish-to-start).', related_name='successors', to='pmo.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='slack',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
