# Generated by Django 4.2.30 on 2026-07-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="taxrate",
            name="unique_tax_rate_country_type_date",
        ),
        migrations.AlterUniqueTogether(
            name="taxrate",
            unique_together={("country", "tax_type", "effective_date")},
        ),
    ]
