# Generated by Django 4.2.30 on 2026-07-10 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0002_remove_taxrate_unique_tax_rate_country_type_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrate",
            name="effective_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
