# Generated by Django 4.2.30 on 2026-07-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0003_alter_taxrate_effective_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrule",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
