# Generated by Django 4.2.30 on 2026-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0004_alter_taxrule_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_ar", models.CharField(blank=True, max_length=100)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=15, max_digits=5),
                ),
                (
                    "zatca_category",
                    models.CharField(
                        choices=[
                            ("S", "Standard Rated"),
                            ("Z", "Zero Rated"),
                            ("E", "Exempt"),
                            ("O", "Out of Scope"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tax_templates",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
