# Generated by Django 4.2.30 on 2026-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(db_index=True, max_length=50)),
                ("item_name", models.CharField(blank=True, max_length=200)),
                ("warehouse", models.CharField(blank=True, max_length=100)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("in", "Receipt"), ("out", "Issue")], max_length=3
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("date", models.DateField(db_index=True)),
                ("reference", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "db_table": "stock_movements",
                "ordering": ["item_code", "date", "id"],
            },
        ),
    ]
