# Generated by Django 4.2.30 on 2026-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepreciableAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("asset_code", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "salvage_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("useful_life_years", models.PositiveSmallIntegerField(default=5)),
                ("purchase_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("straight_line", "Straight Line"),
                            ("declining", "Declining Balance"),
                        ],
                        default="straight_line",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "depreciable_assets",
                "ordering": ["-purchase_date", "name"],
            },
        ),
    ]
