# Generated by Django 4.2.7 on 2026-07-20 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_branch_latitude_alter_branch_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrprofile",
            name="user",
            field=models.OneToOneField(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
