# Generated by Django 4.2.30 on 2026-07-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("iban", models.CharField(blank=True, max_length=40)),
                ("currency", models.CharField(default="SAR", max_length=10)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "bank_accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Deposit"), ("out", "Withdrawal")], max_length=3
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("reconciled", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.bankaccount",
                    ),
                ),
            ],
            options={
                "db_table": "bank_transactions",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
